services:
  warp-ddns:
    build: .
    container_name: xlntb-warp-ddns
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # ▼ 将这里改为 POSIX 时区格式
      - TZ=CST-8
    network_mode: "host"
    volumes:
      - /etc/openclash/proxy_provider:/app/output
      # ▼ 删除 /etc/localtime 那一行
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
